<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "iqtp13db"
 *
 * Auto generated by Extension Builder 2018-09-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'IQ TP13 Datenbank Anerkennungserstberatung NRW',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Uli Dohmen',
    'author_email' => 'edv@whkt.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.9.95',
    'constraints' => [
        'depends' => [
            'typo3' => '6.2.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
