services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ud\Iqtp13db\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Ud\Iqtp13db\Controller\RequestController:
    public: true

  Ud\Iqtp13db\Service\QRCodeGenerator:
    public: true

  IQT\Iqtp13db\Task\StatistikCacheTask:
    public: true
    tags:
      - name: scheduler.task
        label: 'IQT: Statistik-Cache neu berechnen'
        description: 'Berechnet täglich aggregierte Statistiken pro Beratungsstelle und schreibt sie in tx_iqtp13db_domain_model_statistik_cache.'
        additionalFieldProvider: 'IUd\Iqtp13db\Task\StatistikCacheTaskAdditionalFieldProvider'
