services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ud\Iqtp13db\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Ud\Iqtp13db\Controller\RequestController:
    public: true    
